import type { ApiProduct } from "@shared/schema";

export const seedProducts: ApiProduct[] = [
  {
    id: "p1",
    name: "12-Speed Chain — Quick-Link",
    vehicle: "bike",
    category: "Drivetrain",
    price: 29.99,
    rating: 4.7,
    reviewCount: 184,
    stock: "in-stock",
    quantity: 24,
    deliveryEta: "Next-day delivery",
    compatibility: ["Road", "MTB"],
    tags: ["Fast shipping", "Popular"],
    image: "",
    description:
      "Smooth shifting and durable plating for everyday riding and race days. Includes quick-link for easy installation.",
    specs: [
      { label: "Speeds", value: "12" },
      { label: "Connector", value: "Quick-link included" },
      { label: "Finish", value: "Nickel plated" },
    ],
  },
  {
    id: "p2",
    name: "160mm Disc Brake Rotor — Vent",
    vehicle: "bike",
    category: "Brakes",
    price: 24.5,
    rating: 4.6,
    reviewCount: 93,
    stock: "low",
    quantity: 4,
    deliveryEta: "1–2 days",
    compatibility: ["MTB", "Hybrid"],
    tags: ["Heat control"],
    image: "",
    description:
      "Crisp braking with vented channels for better cooling. Designed for consistent performance in wet or dry conditions.",
    specs: [
      { label: "Size", value: "160mm" },
      { label: "Mount", value: "6-bolt" },
      { label: "Weight", value: "~120g" },
    ],
  },
  {
    id: "p3",
    name: "10×2.5 Scooter Tire — Street",
    vehicle: "scooter",
    category: "Wheels & Tires",
    price: 19.0,
    rating: 4.4,
    reviewCount: 71,
    stock: "in-stock",
    quantity: 18,
    deliveryEta: "Next-day delivery",
    compatibility: ["10 inch"],
    tags: ["Easy install"],
    image: "",
    description:
      "A reliable street tire with a smooth center line for low rolling resistance and comfortable commuting.",
    specs: [
      { label: "Size", value: "10×2.5" },
      { label: "Type", value: "Street" },
      { label: "Use", value: "Commuting" },
    ],
  },
];
