import type { ApiProduct } from "@shared/schema";

export const seedProducts: ApiProduct[] = [
  {
    id: "p1",
    name: "12-Speed Chain — Quick-Link",
    partNumber: "ENG-CH-001",
    vehicle: "motorcycle",
    category: "Engine",
    subcategory: "Chain",
    brand: "Renthal",
    price: 29.99,
    rating: 4.7,
    reviewCount: 184,
    stock: "in-stock",
    quantity: 24,
    deliveryEta: "Next-day delivery",
    compatibility: ["Honda CB500X", "Yamaha MT-07", "Kawasaki Ninja 650"],
    tags: ["Fast shipping", "Popular"],
    image: "",
    description:
      "Smooth shifting and durable plating for everyday riding and race days. Includes quick-link for easy installation.",
    specs: [
      { label: "Speeds", value: "12" },
      { label: "Connector", value: "Quick-link included" },
      { label: "Finish", value: "Nickel plated" },
    ],
    features: ["Durable plating", "Easy installation", "Quick-link included"],
  },
  {
    id: "p2",
    name: "160mm Disc Brake Rotor — Vent",
    partNumber: "BRK-RO-001",
    vehicle: "motorcycle",
    category: "Brakes",
    subcategory: "Discs",
    brand: "EBC",
    price: 24.5,
    rating: 4.6,
    reviewCount: 93,
    stock: "low",
    quantity: 4,
    deliveryEta: "1–2 days",
    compatibility: ["Suzuki SV650", "Yamaha MT-07"],
    tags: ["Heat control"],
    image: "",
    description:
      "Crisp braking with vented channels for better cooling. Designed for consistent performance in wet or dry conditions.",
    specs: [
      { label: "Size", value: "160mm" },
      { label: "Mount", value: "6-bolt" },
      { label: "Weight", value: "~120g" },
    ],
    features: ["Vented design", "Better cooling", "Consistent performance"],
  },
  {
    id: "p3",
    name: "Sport Touring Tyre — Front",
    partNumber: "TIR-F-001",
    vehicle: "motorcycle",
    category: "Tires & Wheels",
    subcategory: "Tires",
    brand: "Michelin",
    price: 89.0,
    rating: 4.4,
    reviewCount: 71,
    stock: "in-stock",
    quantity: 18,
    deliveryEta: "Next-day delivery",
    compatibility: ["Honda CB500X", "Kawasaki Versys 650", "Suzuki V-Strom 650"],
    tags: ["Easy install"],
    image: "",
    description:
      "A reliable sport touring tyre with excellent grip and longevity. Ideal for commuting and weekend rides.",
    specs: [
      { label: "Size", value: "120/70ZR17" },
      { label: "Type", value: "Sport Touring" },
      { label: "Use", value: "Road" },
    ],
    features: ["Long mileage", "Wet grip", "Stable handling"],
  },
];
